name: Trigger auto deployment for container-app-dtfar4apejl42

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-dtfar4apejl42-AutoDeployTrigger-72f5e685-b318-4bc0-adaf-8410393ce65e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPDTFAR4APEJL42_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPDTFAR4APEJL42_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPDTFAR4APEJL42_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: containerregistrydtfar4apejl42.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPDTFAR4APEJL42_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPDTFAR4APEJL42_REGISTRY_PASSWORD }}
          containerAppName: container-app-dtfar4apejl42
          resourceGroup: test-space-rg-2
          imageToBuild: containerregistrydtfar4apejl42.azurecr.io/container-app-dtfar4apejl42:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


